name = "anode-rust-worker"
type = "rust"
account_id = "7bf23342f21baa5ebfc7bc7b74f5a1f2"
workers_dev = true

[build]
command = "cargo install -q worker-build && worker-build --release"

# Environment variables
[vars]
NODE_ENV = "production"
SERVICE_NAME = "aNode Paymaster Worker (Rust)"

# Optional: Add KV namespace for caching (if needed in future)
# [[kv_namespaces]]
# binding = "ANODE_CACHE"
# id = "your-kv-namespace-id"
