name = "anode-rust-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-18"

[build]
command = "cargo install -q worker-build && worker-build --release"

# Environment variables
[vars]
NODE_ENV = "production"
SERVICE_NAME = "aNode Paymaster Worker (Rust)"
