name = "anode-rust-simple"
type = "rust"
account_id = "7bf23342f21baa5ebfc7bc7b74f5a1f2"
workers_dev = true

[build]
command = "wasm-pack build --target web --out-dir build/pkg"

# Environment variables
[vars]
NODE_ENV = "production"
SERVICE_NAME = "aNode Rust Paymaster Worker"
